INSERT INTO quests (quest_name, description, reward, is_extra, img_path) VALUES
	('Exploring a dungeon', 'Finishing a Teamwork week', 1, FALSE, '../static/img/q_dungeon.png'),
	('Entering the arena', 'Do a presentation on a meet-up', 15, FALSE, '../static/img/q_arena.png'),
	('Creating an enchanted scroll', 'Creating extra material for the current TW/SI topic (should be revised by mentors)',
	    5, TRUE, '../static/img/q_scroll.png'),
	('Helping the city guard', 'Helping in presenting the house rules on Orientation Week', 2, FALSE, '../static/img/q_guard.png'),
	('Fruitful opportunism', 'Helping to facilitate a mentor organized workshop', 3, TRUE, '../static/img/q_opportunism.png'),
	('Forging weapons', 'Organizing a workshop for fellow students', 7, TRUE, '../static/img/q_weapons.png'),
	('Mastering the mornings', 'Attend 20 consecutive TW days without being late or absent', 5, FALSE, '../static/img/q_mornings.png'),
	('Making arrowheads', 'Create a Kahoot question list with at least 10 questions in a Codecool related topic', 3, TRUE,
	    '../static/img/q_arrowheads.png'),
	('Magic the gathering', 'Organize a spare time event for the room (for at least 20 people) recorded by a selfie', 10,
	    TRUE, '../static/img/q_gathering.png'),
	('Slaying a dragon', 'Doing the first Personal Assessment attempt in a module (regardless of the result)', 5, FALSE,
	    '../static/img/q_dragon.png'),
	('Showing off', 'Participate in a presentation/Q&A on intro day', 2, FALSE, '../static/img/q_showing.png'),
	('Recruiting novices', 'Taking part in the student screening', 2, FALSE, '../static/img/q_novice.png'),
	('Starter pack', 'Finishing the orientation week', 3, FALSE, '../static/img/q_starter.png'),
	('Spotting a trap', 'Spot a major mistake in the material which blocks understanding (first students who discovers)',
	    1, TRUE, '../static/img/q_trap.png'),
	('Solving the magic puzzle', 'Finishing an SI week''s assignments before the TW week', 1, FALSE, '../static/img/q_puzzle.png'),
	('Treasure hunt!', 'Solving the riddle announced random times in the given time frame', 25, TRUE,
	    '../static/img/q_treasure.png'),
	('Taming a pet', 'Doing a 10 minutes long demo about an IT pet project for his/her room', 3, TRUE, '../static/img/q_pet.png'),
	('Stuffing the rooster', 'Come up with 7 good attendance questions (room decides whether they''re acceptable)', 1,
	    FALSE, '../static/img/q_rooster.png'),
	('Visiting the wiseman', 'Going to a company interview', 3, FALSE, '../static/img/q_wiseman.png');

